[package]
name = "meminfo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "meminfo"
path = "src/lib.rs"

[dependencies]

[features]
utf8-unchecked = []
